spring:
    application:
        name: anag

server:
    port: 9081
    contextPath: /anag

eureka:
    client:
      serviceUrl:
        defaultZone: ${EUREKA_URI:http://localhost:8761/registry/eureka}
    instance:
      preferIpAddress: true
      appname: anag
      statusPageUrlPath: ${server.contextPath}/info
      healthCheckUrlPath: ${server.contextPath}/health
      metadata-map:
          contextPath: ${server.contextPath}
